pipeline:
  name: Hello World Kotlin Pipeline
  jobs:
    - name: Hello World Kotlin Job
      working-directory: examples/ipc/kotlin
      steps:
        - name: Hello World Kotlin Step
          shell: none
          with:
            name: User
          run: |
            kotlinc Extension.kt
            kotlin ExtensionKt
        - name: Hello World Kotlin Captured Properties
          run: |
            echo captured extension property \${{ extension.property.1 }} = "${{ extension.property.1 }}"
            echo captured extension property \${{ extension.property.2 }} = "${{ extension.property.2 }}"
