pipeline:
  name: Hello World Lua Pipeline
  jobs:
    - name: Hello World Lua Job
      working-directory: examples/ipc/lua
      steps:
        - name: Hello World Lua Step
          shell: none
          with:
            name: Test User
          run: lua extension.lua
        - name: Hello World Lua Output Variables
          run: |
            echo output extension variable \${{ lua_extension_variable_1 }} = "${{ lua_extension_variable_1 }}"
            echo output extension variable \${{ lua_extension_variable_2 }} = "${{ lua_extension_variable_2 }}"
