pipeline:
  name: Hello World Lua Pipeline
  jobs:
    - name: Hello World Lua Job
      working-directory: examples/ipc/lua
      steps:
        - name: Hello World Lua Step
          shell: none
          with:
            name: Test User
          run: lua extension.lua
        - name: Hello World Lua Captured Properties
          run: |
            echo captured extension property \${{ extension.property.1 }} = "${{ extension.property.1 }}"
            echo captured extension property \${{ extension.property.2 }} = "${{ extension.property.2 }}"
