pipeline:
  name: all
  enabled: false
  #
  # Disabled by default
  #
  # Python may not be installed
  # Node may not be installed
  # Go may not be installed
  # Groovy may not be installed
  #
  jobs:
    - name: all
      steps:
        - name: examples/ipc/go/go-extension.yaml
          run: $PIPELINER examples/ipc/go/go-extension.yaml
        - name: examples/ipc/groovy/groovy-extension.yaml
          run: $PIPELINER examples/ipc/groovy/groovy-extension.yaml
        - name: examples/ipc/java/java-extension.yaml
          run: $PIPELINER examples/ipc/java/java-extension.yaml
        - name: examples/ipc/js/js-extension.yaml
          run: $PIPELINER examples/ipc/js/js-extension.yaml
        - name: examples/ipc/kotlin/kotlin-extension.yaml
          run: $PIPELINER examples/ipc/kotlin/kotlin-extension.yaml
        - name: examples/ipc/python/python-extension.yaml
          run: $PIPELINER examples/ipc/python/python-extension.yaml
