pipeline:
  name: all
  enabled: false
  #
  # Disabled by default
  #
  # Python may not be installed
  # Node may not be installed
  # extension.go may not be compiled
  #
  jobs:
    - name: all
      steps:
        - name: examples/ipc/python/python-extension.yaml
          run: $PIPELINER examples/ipc/python/python-extension.yaml
        - name: examples/ipc/js/js-extension.yaml
          run: $PIPELINER examples/ipc/js/js-extension.yaml
        - name: examples/ipc/go/go-extension.yaml
          run: $PIPELINER examples/ipc/go/go-extension.yaml


