pipeline:
  name: Hello World Java Pipeline
  jobs:
    - name: Hello World Java Job
      working-directory: examples/ipc/java
      steps:
        - name: Hello World Java Step
          shell: none
          with:
            name: Test User
          run: |
            javac Extension.java
            java -cp . Extension
        - name: Hello World Java Captured Properties
          run: |
            echo captured extension property \${{ extension.property.1 }} = "${{ extension.property.1 }}"
            echo captured extension property \${{ extension.property.2 }} = "${{ extension.property.2 }}"
