pipeline:
  name: SSH directive pipeline
  jobs:
    - name: SSH directive job
      steps:
        - name: SSH directive step
          with:
            user: <USER>
            server: <SERVER>
            user_server: ${{ user }}@${{ server }}
          run: |
            --ssh ${{ user_server }} uptime | xargs > $uptime
            echo Uptime: ${{ uptime }}
