pipeline:
  name: Hello World Pipeline
  enabled: true
  jobs:
    - name: Hello World Job
      enabled: true
      steps:
        - name: Hello World Step 1
          id: hello-world-step-1
          enabled: true
          with:
            variable_1: step 1 variable 1
            variable_2: step 1 variable 2
          run: |
            echo "\${{ variable_1 }}" = "${{ variable_1 }}"
            echo "\${{ variable_2 }}" = "${{ variable_2 }}"
        - name: Hello World Step 2
          id: hello-world-step-2
          enabled: true
          with:
            variable_1: step 2 variable 1
            variable_2: step 2 variable 2
          run: |
            echo "\${{ variable_1 }}" = "${{ variable_1 }}"
            echo "\${{ variable_2 }}" = "${{ variable_2 }}"
        - name: Hello World Step 3
          id: hello-world-step-3
          enabled: true
          run: |
            echo "\${{ hello-world-step-1.variable_1 }}" = "${{ hello-world-step-1.variable_1 }}"
            echo "\${{ hello-world-step-1.variable_2 }}" = "${{ hello-world-step-1.variable_2 }}"
            echo "\${{ hello-world-step-2.variable_1 }}" = "${{ hello-world-step-2.variable_1 }}"
            echo "\${{ hello-world-step-2.variable_2 }}" = "${{ hello-world-step-2.variable_2 }}"
