pipeline:
  name: Hello World Nim Pipeline
  jobs:
    - name: Hello World Nim Job
      working-directory: examples/ipc/nim
      steps:
        - name: Hello World Nim Step
          shell: none
          with:
            name: Test User
          run: |
            nim c -d:release -o:extension extension.nim
            ./extension
        - name: Hello World Nim Output Variables
          run: |
            echo output extension variable \${{ nim_extension_variable_1 }} = "${{ nim_extension_variable_1 }}"
            echo output extension variable \${{ nim_extension_variable_2 }} = "${{ nim_extension_variable_2 }}"
