pipeline:
  name: Hello World Rust Pipeline
  jobs:
    - name: Hello World Rust Job
      working-directory: examples/ipc/rust
      steps:
        - name: Hello World Rust Step
          shell: none
          with:
            name: Test User
          run: |
            rm -Rf extension
            rustc extension.rs -o extension
            ./extension
        - name: Hello World Rust Output Variables
          run: |
            echo output extension variable \${{ rust_extension_variable_1 }} = "${{ rust_extension_variable_1 }}"
            echo output extension variable \${{ rust_extension_variable_2 }} = "${{ rust_extension_variable_2 }}"
