pipeline:
  name: Hello World JavaScript Pipeline
  jobs:
    - name: Hello World JavaScript Job
      working-directory: examples/ipc/js
      steps:
        - name: Hello World JavaScript Step
          shell: none
          with:
            name: Test User
          run: node extension.js
        - name: Hello World JavaScript Output Variables
          run: |
            echo output extension variable \${{ js_extension_variable_1 }} = "${{ js_extension_variable_1 }}"
            echo output extension variable \${{ js_extension_variable_2 }} = "${{ js_extension_variable_2 }}"
