pipeline:
  name: Hello World JavaScript Pipeline
  jobs:
    - name: Hello World JavaScript Job
      working-directory: examples/ipc/js
      steps:
        - name: Hello World JavaScript Step
          shell: none
          with:
            name: Test User
          run: node extension.js
        - name: Hello World JavaScript Captured Properties
          run: |
            echo captured extension property \${{ extension.property.1 }} = "${{ extension.property.1 }}"
            echo captured extension property \${{ extension.property.2 }} = "${{ extension.property.2 }}"
